name: Beats2Build build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: sudo apt-get install -y p7zip-full nsis
      
    - name: Building using pyinstaller
      run: |
        cp .github/*.spec .
        docker run -v "${{ github.workspace }}:/src" batonogov/pyinstaller-windows:python_3.9
        
    - name: Download and unpacking ffmpeg
      run: |
        wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z 
        7z e ./ffmpeg-release-full-shared.7z -odist/Beats2Fun -ir\!bin
        
    - name: Create windows installer
      run: makensis .github/Beats2Fun.nsi
      
    - uses: actions/upload-artifact@v2
      with:
        name: Beats2Fun
        path: ./dist/Beats2Fun
      
    - uses: actions/upload-artifact@v2
      with:
        name: Beats2Fun-setup.exe
        path: ./dist/Beats2Fun-setup.exe
    