name: Beats2Build build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install 7z
      run: sudo apt-get install -y p7zip-full  
      
    - name: Download ffmpeg
      run: wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
      
    - name: Unpack ffmpeg
      run: 7z e ./ffmpeg-release-full-shared.7z -oResources/ffmpeg -ir\!bin

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: .github/Beats2Fun.spec
        
    - name: Create installer
      uses: joncloud/makensis-action@v3.6
      with:
        script-file: .github/Beats2Fun.nsi
    
    - uses: actions/upload-artifact@v2
      with:
        name: Beats2Build-setup.exe
        path: ./dist/